version: 2.1
orbs:
  slack: circleci/slack@4.3.0
jobs:
  notify:
    docker:
    - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Running in a Unique Container
          command: |
            node -v
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Copy config.js
          command: |
            echo module.exports = { TOKEN: \'$TOKEN\' } > config.js
      - run:
          name: Run Tests
          command: npm test
      - slack/notify:
            event: fail
            mentions: '@EngineeringTeam'
            template: basic_fail_1
        - slack/notify:
            event: pass
            template: success_tagged_deploy_1
