const DummyData = [
  {
    rating: 4,
    name: 'Mary Anne',
    date: '2021-02-23T02:49:03.102Z',
    reviewBody: 'Lorem ipsum dolor sit amet, mea no congue graeco percipit, case nobis recusabo pri ex. Ullum fabellas verterem mea et, vel partiendo assueverit ei. Vidit probatus cu quo, at fugit adversarium mea. Vel in suas ignota fabulas, erat tantas facilis id cum, pri et vero putent verear. Eam amet dicta laoreet et. Mea omnium reprimique cu, habeo iriure ornatus sea ad.',
    summary: 'Nemo ratione deserunt',
    response: 'Was this review helpful?',
  },
  {
    rating: 5,
    name: 'Billy Raven',
    date: '2021-02-24T05:35:11.102Z',
    reviewBody: 'Ullum fabellas verterem mea et, vel partiendo assueverit ei. Vidit probatus cu quo.',
    summary: 'Pro iusto oratio ',
    response: 'Was this review helpful?',
  },
  {
    rating: 3,
    name: 'John Nathan',
    date: '2021-02-23T04:15:37.102Z',
    reviewBody: 'Vel in suas ignota fabulas, erat tantas facilis id cum, pri et vero putent verear.',
    summary: 'His sanctus consequuntur no',
    response: 'Was this review helpful?',
  },
  {
    rating: 4,
    name: 'Lizzy Ramos',
    date: '2021-02-27T06:55:19.102Z',
    reviewBody: 'Eam amet dicta laoreet et. Mea omnium reprimique cu, habeo iriure ornatus sea ad.',
    summary: 'Doctus scripserit philosophia duo ne.',
    response: 'Was this review helpful?',
  },
  {
    rating: 3,
    name: 'Kyle Gogurt',
    date: '2021-02-23T01:44:54.102Z',
    reviewBody: 'At usu vide sententiae, pri no stet brute. Vel nihil saepe ei, duo quem audiam at. Perpetua similique voluptatibus cu vim. ',
    summary: 'Ad tollit percipit pri.',
    response: 'Was this review helpful?',
  },
  {
    rating: 2,
    name: 'Natasha Spikes',
    date: '2021-02-26T01:49:03.102Z',
    reviewBody: 'In qui case recusabo. Malorum euripidis gloriatur vim ut. Eu vim tantas labores, qui an libris volumus epicuri. Te quo tota nominavi scribentur.',
    summary: 'quo utinam omnium audiam cu.',
    response: 'Was this review helpful?',
  },
  {
    rating: 4,
    name: 'Ian Gatorade',
    date: '2021-02-23T07:23:44.102Z',
    reviewBody: 'Est ut odio ocurreret, lorem virtute ex usu, mel iriure liberavisse at. Per ex modo virtute copiosae, laoreet albucius qui in. His vocent scripserit eu.',
    summary: 'Ad tollit percipit pri.',
    response: 'Was this review helpful?',
  }];
export default DummyData;
